### ISSUE TITLE
Status reports 

### ISSUE THREAD

**Issue by Belgmeister** [bvrielink/tuyasmartplug.sh#3]

**Comment by bvrielink** [comment]
> _No description provided._

As no description is provided I will close this issue. Please create a new issue with some description if necessary.

**Comment by Belgmeister** [comment]
Apologies. I started writing this issue but didn't finish as I decided to get some clearing info and "confirm" the root of the issue before bothering you with it. Wasn't aware it would still post it. Creating new issue now after some testing!
