### ISSUE TITLE
Issue with "status" argument on multiple socket Tuya

### ISSUE THREAD

**Issue by Belgmeister** [bvrielink/tuyasmartplug.sh#4]
Hi bvrielink,

I came across your script on the Tuyasmartplug feature request page and have been trying to implement it.
First of all, thanks for making it!

I noticed my PSU control status was constantly green while the socket was "OFF"
After some testing I noticed the status argument returned "ON" when the socket '2' was still on, while socket '1' was already off.
Turning both off returns a proper status of "OFF"
ON/OFF/STATUS argument behave as expected besides this point.

However PSU control still reports a green icon even when both sockets are set to "OFF" and the Status argument echo "tuya smartplug is turned OFF", 
It does behave as expected when I try to turn it off, but the status never changes from green, to red.

Could you help me how to modify the script for it to fetch the status for '1' instead of '2' see if that helps?

- Attached preview of my PSU control settings and Tuyasmartplug settings
- The DEBUG Log shows the following STATUS line for the Tuya plug when both are OFF:

> [2021-12-18 12:05:12,215] DEBUG: Status: {'dps': {'1': False, '2': False, '9': 0, '10': 0, '17': 1, '18': 0, '19': 0, '20': 2306, '21': 1, '22': 608, '23': 29500, '24': 16924, '25': 2470, '26': 0, '38': 'memory', '41': '', '42': ''}}

![Screenshot 2021-12-18 132445](https://user-images.githubusercontent.com/64487458/146641020-a0b7bb38-dec6-41f3-a1c2-87d10137bcb0.png)
![Screenshot 2021-12-18 132619](https://user-images.githubusercontent.com/64487458/146641022-4d70c618-f4ad-4d8a-ae42-d5a237aeb227.png)

**Comment by bvrielink** [comment]
Hi Belgmeister. Please try this:

![image](https://user-images.githubusercontent.com/8544667/146641590-9016f476-e578-4407-885b-78e5f72d7168.png)

The status option is more for debugging purposes and not something I use myself.

**Comment by shigadeyo** [comment]
The script and this configuration seems to be working for me. Thank you!

**Comment by Belgmeister** [comment]
The "internal" method seems to work as expected, thanks for the suggestion.

**Comment by bvrielink** [comment]
Thanks for the update.
